server:
  port: 8091

spring:
  profiles:
    active:
      - dev
  application:
    name: natsufumij-yuusha
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations:
    - classpath:hut/natsufumij/yuusha/**/*Mapper.xml
